before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: iC6sWxZpiEUARfgZ3Yx7JcFS4by8QvPxtmtavnzhNXmKtp2Txq8+55wyFd6FQhcxnL2zokMUxFZYMO2EXjhoLDB58HizG9CyvzBMDThNKwQiqsLJXlE6SKMMweIj/1NOOeiI+NX75uIrRP79Xj45aEP0AlPFvCUXQC+2V3t9grQszWlhBPU2VxJ0seYsCk19tWkzXD5gjG8s+E/grhJl+cLmNN8yfcWW/yI6kB9zIZr8J53pWsBKbTtMBsUDQl2I2Vk++ChTxbOFnn2xVt9zIU3lCQ4yETCq453CQfUpG2VtjeAWdosLgNmWsZC7WnBFMvi0KMkfqT+Wss1/GZb124bgT5RKGodZsLGnGcccchkPgRgkxThnZQuz85d3sr5GRJo2iax6+VqlrkeykG5FOEQEsJZhYBML8gZgvAkbO69CQxVlp1MK5IdZ7+2t0fRelu1elGDB4cMt0dHqdEgRQRJWjeK7/u8IvCAZ2tkVH1jqZjFbQRlqCLajJxiytBYfn0md2FloJRv70jY6gRNEUp9Ym+qxmvyVf1x6IE7iCrEY7l0HSezLnLUbTHBF/8jcIK5V1V62LbYjsFbuL+40Z6cjLpi5LcsmG7GvOk5gSsBfZUSyxMNNnF1hLmfJVDzxFWwRT+ND40BGC7OEbdQmBLkDB2vsK/khbIOg47AnAI4= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
